### PR TITLE
RF/ENH: Update to use ioHub's serial.Pstbox

### PR DESCRIPTION
**Pull request by hoechenberger**
This updates the demo to use ioHub's new serial.Pstbox device instead of the previous generic serial.Serial interface. It demonstrates how to acquire response times for button presses and how to operate the lamps.

### CODE REVIEW

**Comment by hoechenberger** [comment]
Please do not merge yet, I will probably change some more minor things and rebase!

**Comment by isolver** [comment]
OK. Let me know when you want the merge done. Thanks Richard!

**Comment by hoechenberger** [comment]
Okay I think it's ready to merge as soon as Travis finishes. Rebased on current isolver/psychopy.

**Comment by isolver** [comment]
I accepted the pull request. thanks.

So should isolver/psychopy master now have the latest changes to all files
related to the PstBox device addition?

I ask because I am trying to look into the hdf5 file issue you are getting
if an existing hdf5 file exists. Can you confirm you still get this error?

Thanks Richard!

**Comment by isolver** [comment]
Also, does Pstbox device ever actually create SerialInputEvent types, or
just  PstboxButtonEvent types. I'm cleaning up the file a bit and noticed
this. I do not see anywhere that Pstbox creates SerialInputEvent , so I was
going to remove it from the lists.

Thanks,

Sol

**Comment by isolver** [comment]
Hi Richard,

OK, I think I fixed that datastore issue (related to >1 device class being
in same device folder). Can yu test with the real PST box and see if it is
OK now?

I also updated the code and demo a bit to work around issues I had when
connecting to a non pstbox serial device on my pc (that was the only way to
atleast get the pstbox device to init and the demo to start running so I
could try to debug the issue).

Please get latest source from isolver/psychopy master branch.

Thank you!

**Pull request merged**
