### PR TITLE
BF: Convert return data to list

### PR DESCRIPTION
**Pull request by hoechenberger**
Checking if `r` is an empty list will natuarlly fail if, for example, `r` is a NumPy array:

```
>>> l = [1, 2,3]
>>> if l:
...     print "YUP!"
...
YUP!
>>> import numpy as np
>>> a = np.array(l)
>>> if a:
...     print "YUP!"
...
Traceback (most recent call last):
  File "<ipython-input-8-74924ebbdc6d>", line 1, in <module>
    if a:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Therefore, we should try to (temporarily) convert the return data to a list before checking the truth value:
```
>>> if list(a):
...     print "YUP!"
...
YUP!
>>>
```
This bug was discovered when trying to change existing code to take advantage of msgpack-numpy.

### CODE REVIEW

**Comment by hoechenberger** [comment]
All right. Now I don't know what to do anymore :D

At any rate, like I said before: The current code does not work if the server returns a NumPy array. But I do want to return NumPy arrays sometimes ... I will try to either upload the code that's causing problems for me, or to put together a minimal example to illustrate the problem.

**Comment by hoechenberger** [comment]
Okay, here we go again.
So in ``iohub.devices.serial.Pstbox``, I have a method called ``getLampState()`` (see https://github.com/hoechenberger/psychopy/blob/pstbox-subclass/psychopy/iohub/devices/serial/__init__.py#L533). All it does is return ``self._lamp_state``, which is a NumPy array of bools, each element representing the state of a lamp (``False``: off, ``True``: on).

If I call this method, at some time ``iohub.client.DeviceRPC.__call__()`` will be invoked, and its first line -- ``r = self.sendToHub(('EXP_DEVICE','DEV_RPC',self.device_class,self.method_name,args,kwargs))`` -- will, for example, set ``r`` to:
```
['DEV_RPC_RESULT', array([False, False, False, False, False], dtype=bool)]
```

``r`` is then further processed in the method:
```
        r=r[1:]
        if len(r)==1:
            r=r[0]
```
which yields:
```
array([False, False, False, False, False], dtype=bool)
```
If now, on line 63, it is checked whether ``r`` is ``True`` or not:
```
        if r and self.method_name == 'getEvents':
```
this will fail, because a NumPy array with more than one element does not have an umambiguous single truth value:
```
---> 63         if r and self.method_name == 'getEvents':
     64             asType='namedtuple'
     65             if 'asType' in kwargs:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
I hope this made the problem more clear. I do not want to change what my method returns, because I __want__ it to return that NumPy array.

**Comment by isolver** [comment]
I guess the question is whether device.getEvents() should be returning a
numpy array. For all current devices it returns a list of event field value
lists. Not sure if a device should really ever override device.getEvents()
anyhow, unless there is a real need for supporting that.

So maybe you could have a different method for the device that returns the
numpy array(s) you want from the device. i.e.:

np_array = device.getArrayData()

or something.

I may not understand what the (very possibly value) reason is for your
device to no just let iohub do its thing and handle what is returned by
getEvents(). Can you please provide more info if possible?

Thanks again.

**Comment by isolver** [comment]
OK, forget the below, I think I see what the issue is.

The line:

if r and self.method_name == 'getEvents':

should be changed to :

if self.method_name == 'getEvents' and r:

since the logic should only be applied to the return value from a
device.getEvents() call.

Right now it is always checking r, instead of checking that 'getEvents' was
called and /then/ checking r.

Do you want to make this fix and do a pull request to isolver/psychopy, or
do you want me to fix it and push to psychopy/psychopy?

Thanks!


--------- initial reply below---------
Anything returned from a call to the iohub server is wrapped in a list.
This is done by iohub itself, and is why the code you reference is there.
So unless your code is somehow bypassing the standard iohub server DEV_RPC
handling and thus the format DEV_RPC_RESULT is returned as.

So if you have a function running on the iohub server and it returns a
numpy array, say 'my_np_array', what the psychopy iohub client will get as
the return value is [my_np_array,] which is extracted and returned to the
user as just 'my_np_array'.

If this is not happening for you, please let me know where to get your
latest psychopy source with the changes to it, and the test script, and I
will look into why this is happening.

**Comment by isolver** [comment]
OK, so I made that change so 'r' is only checked if the rpc method was 'getEvents', which was the original intent anyhow. ;)

You can get it from isolver/psychopy master (psychopy.iohub.client.\__init__.py file).

Once you let me know this fixes your use cases I will do a pull request to psychopy.

Thanks again.

**Comment by hoechenberger** [comment]
Hello!

On Mon, Jan 5, 2015 at 8:30 PM, Sol Simpson <notifications@github.com>
wrote:

> OK, so I made that change so 'r' is only checked if the rpc method was
> 'getEvents', which was the original intent anyhow. ;)
>

Believe me or not, but this was actually the first fix I thought of ;) But
I immediately discarded the thought, thinking "Naaah, that's just hiding
the problem, not really fixing it." Guess I should have thought some more,
would've saved a lot of time ;)


> You can get it from isolver/psychopy master
> (psychopy.iohub.client.__init__.py file).
>
> Once you let me know this fixes your use cases I will do a pull request to
> psychopy.
>
>
Great, thanks. Btw I discovered one can easily pull in changes from a
remote repo without adding a remote origin first; I simply had to to:

     git pull https://github.com/isolver/psychopy.git

Really neat.

Can only test the code later today, but I think it's gonna work just fine.

    Richard

**Comment by isolver** [comment]
On Tue, Jan 6, 2015 at 3:15 AM, Richard Höchenberger <
notifications@github.com> wrote:

> eve me or not, but this was actually the first fix I thought of ;) But
> I immediately discarded the thought, thinking "Naaah, that's just hiding
> the problem, not really fixing it." Guess I should have thought some more,
> would've saved a lot of time ;)
>

Sometimes the I am blind to the obvious; sorry for not clicking into this
sooner. I am surprised it has not bitten anyone (including me) sooner!

Thanks for pushing on the issue, and your patience while helping to figure
out what the real issue was.

Sol

**Pull request closed without merging**
